use si@Nom_Swiss
go

-- HACE LA BASE DE DATOS MONOUSUARIO
ALTER DATABASE si@Nom_Swiss SET SINGLE_USER


DBCC CHECKDB (Si@Nom_Swiss, repair_fast)
go

-- HACE LA BASE DE DATOS NUEVAMENTE MULTIUSUARIO
ALTER DATABASE si@Nom_Swiss SET MULTI_USER